trigger:
- main

# Use the default Microsoft-hosted pool
pool:
  vmImage: 'ubuntu-latest' 

steps:
# This task simply prints a success message and executes.
- script: |
    echo "Pipeline successfully started and completed a simple task."
    echo "Success!"
  displayName: 'Simple Success Script'